name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: clark-labs-inc/.github/.github/workflows/rust-library.yml@760f8e6d1de08f228eae0c0fcb584d5da7ddddbb
